name: CI/CD Dev

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
              docker build \
              --build-arg APP_PORT=${{ secrets.PROD_PORT }} \
              --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_PROD_API_URL }} \
              -t kevinirawand/sia-fe-prod:latest .

      - name: Push Docker Image
        run: docker push kevinirawand/sia-fe-prod:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull kevinirawand/sia-fe-prod:latest
            docker stop sia-fe-prod || true
            docker rm sia-fe-prod || true
            docker run -d --name sia-fe-prod \
              -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_PROD_API_URL }} \
              -e PORT=${{ secrets.PROD_PORT }} \
              -p ${{secrets.PROD_PORT}}:${{secrets.PROD_PORT}} \
              kevinirawand/sia-fe-prod:latest