name: 🚀 CI/CD Staging

on:
  push:
    branches:
      - stg
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install Dependencies
        run: npm install

      - name: 🔐 Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🛠 Build Docker Image
        run: docker build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} -t nevmock/sia-fe-stag:latest .

      - name: 📤 Push Docker Image
        run: docker push nevmock/sia-fe-stag:latest

      - name: 🚢 Deploy to VPS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔁 Pulling latest Docker image..."
            docker pull nevmock/sia-fe-stag:latest

            echo "🛑 Stopping and removing old container (if exists)..."
            docker stop sia-fe-stag || true
            docker rm sia-fe-stag || true

            echo "🚀 Running new container..."
            docker run -d \
              --name sia-fe-stag \
              --restart unless-stopped \
              -p "${{ secrets.PORT }}":3000 \
              nevmock/sia-fe-stag:latest

            echo "🧹 Cleaning up unused Docker resources..."
            docker system prune -f

            echo "✅ Deployment to Staging environment completed successfully!"